[default]
debug = true
LOG_LEVEL = "INFO"
DEFAULT_LOCALES_PATH = "src\\date_calc\\locale"
ICON_PATH = "src\\date_calc\\assets"
TIMEZONE = "America/Recife"

[production]
debug = false
LOG_LEVEL = "WARNING"

[development]
debug = true
LOG_LEVEL = "DEBUG"
